return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")
        configs.setup({
            ensure_installed = {
                "c",
                "lua",
                "python",
                "rust",
                "cpp",
                "typescript",
                "javascript",
                "query",
                "html",
                "css",
                "elixir",
                "gleam",
                "gotmpl",
                "haskell",
                "svelte",
                "astro",
                "wgsl",
                "zig",
                "go",
                "hlsl",
                "glsl",
                "odin",
                "nim",
                "fish",
                "bash",
                "c_sharp",
                "fsharp",
                "dockerfile",
                "json",
                "make",
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
            auto_install = false,
            ignore_install = {},
            modules = {},
        })
    end,
}
